# Generated by Django 6.0.6 on 2026-06-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0002_movimientofinanciero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoFinanciero',
        ),
    ]
